[package]
name = "bigerror"
version = "0.6.0"
edition = "2021"
description = "handle big errors ¯\\_(ツ)_/¯"
license = "MIT"

[features]
default = ["std"]
std = ["error-stack/std", "error-stack/anyhow"]
spantrace = ["error-stack/spantrace"]
eyre = ["error-stack/eyre"]
serde = ["error-stack/serde"]
hooks = ["error-stack/hooks"]
grpc=["tonic", "tonic-types"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.4.1"
thiserror = "1"
tracing = "0.1"
tonic = { version = "0.10", optional = true }
tonic-types = { version = "0.10", optional = true }
