[package]
name = "bigerror"
version = "0.3.0"
edition = "2021"
description = "handle big errors ¯\\_(ツ)_/¯"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.3.1"
thiserror = "1.0.43"
tracing = "0.1.37"
